## EXCEL TEMPLATE CONVERSION PARAMETERS
# Specify your input excel file to convert and place it in 'json_schemas/input_files'
input_excel_file: data.xlsm 
## JSON SCHEMA VALIDATOR PARAMETERS
# Name of metadata category
category: projects

# Name of input data file to validate
input_file_name: projects_test.json